# **Assignment 5 Solutions** #



### **Q1. Implement a Union-Find Data Structure**  ###

In lecture 6 we discussed Union-Find Data structures. The lecture was based on these [slides](https://www.cs.princeton.edu/courses/archive/spr09/cos226/lectures/01UnionFind.pdf). The slides contain Java code fo the Union-Find operations. For this assignment you should implement a Python class that implements a Union-Find Data Structure that uses weighting and path compression. Essentially this amounts to translating the code in the slides using the same specifications. Make sure you review the material and understand what the code does, and how it works. 











In [1]:
# your implementation goes here

class UnionFind:
  
  def __init__(self, n):
    self.id = list(range(n))
    self.sz = [1]*n

  def root(self,i):
    while (i != self.id[i]): 
      id[i] = id[id[i]];       #this is for path compression
      i = self.id[i]

    return i

  def find(self,p,q):
    return (self.root(p) == self.root(q))

  def unite(self,p,q):
    i = self.root(p)
    j = self.root(q)

    # weighted version
    if self.sz[i]<self.sz[j]:
      self.id[i] = j
      self.sz[j] = self.sz[j]+self.sz[i]
    else:
      self.id[j] = i
      self.sz[i] = self.sz[i]+self.sz[j]




In [2]:
S = UnionFind(5)
print(S.id)
print(S.sz)

print(S.find(3,2))

S.unite(3,2)

print(S.id)
print(S.sz)

[0, 1, 2, 3, 4]
[1, 1, 1, 1, 1]
False
[0, 1, 3, 3, 4]
[1, 1, 1, 2, 1]


### **Q2. Random Permutation**

Implement a function *randperm* that takes as input a number $n$, and returns a random permutation of the numbers [0...n-1]. This was covered in lecture 7. Your implementation should use $O(1)$ space in addition to the space needed for the output.  (Note: you can use any random number generator functions from Python's *random* module, but you have to give you own implementation for randperm)

In [3]:
# your implementation goes here

import random

def randperm(n):
  prm = list(range(n))

  for j in range(n):

    # random number in (0,n-j)
    k = random.randrange(n-j)
    
    tmp = prm[k]
    prm[k] = prm[n-1-j]
    prm[n-1-j] = tmp

  return prm
    


In [4]:
randperm(5)

[0, 4, 3, 2, 1]

### **Q3. Adjacency matrices, powers, numpy** <br>
(this exercise should be useful for your mini-project)

![alt text](https://drive.google.com/thumbnail?id=1tIyXRGiQvMv-1EcJxzkQS2MpMNL9hUOA
)

Consider the above graph [(also here)](https://drive.google.com/file/d/1tIyXRGiQvMv-1EcJxzkQS2MpMNL9hUOA/view?usp=sharing).

The following exercise should be **repeated twice**.  For the given directed graph and for the same graph where all edges have no directions. 


**(a)** Create a numpy array containing the adjacency matrix $A$ for the graph.

**(b)** A sequence of nodes $v_1,v_2,...,v_k$ is called a walk on graph $G$, if $(v_i,v_{i+1})$ is an edge in $G$. The length of a walk with $k$ vertices is defined to be $k-1$.  In the above graph pick a pair of nodes $(i,j)$, and report all different walks of length 3 from $i$ to $j$. (That is find, all the ways of going from $i$ to $j$ in 3 steps). 

**(c)** Using numpy, calculate $A^3$, the third power of the adjacency matrix. Read the entry $(i,j)$ of this matrix. What do you observe?

In [5]:
# the following demonstrates the answer for the directed graph

# your code goes here
import numpy as np

A = np.zeros([10,10])

A[0,2] = 1
A[1,9] = 1
A[2,7] = 1
A[3,0] = 1
A[3,5] = 1
A[4,1] = 1
A[4,2] = 1
A[5,4] = 1
A[6,4] = 1
A[7,1] = 1
A[7,8] = 1
A[8,5] = 1
A[8,9] = 1
A[9,6] = 1
A[9,8] = 1

A3 = np.linalg.matrix_power(A,3)

# A3(i,j) is equal to the number of walks of length 3 between (i,j)

print(A3)

[[0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 2.]
 [0. 1. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0. 2. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1. 0. 2. 0. 2. 0.]
 [0. 1. 1. 0. 1. 1. 0. 0. 0. 1.]
 [0. 1. 1. 0. 1. 0. 1. 0. 1. 0.]]


In [6]:
# the following demonstrates the answer for the undirected graph

# to avoid re-typing all opposite edges, I will use the matrix transpose
# transpose(A) is the array with the edges flipped
# then summing up the two matrices gives all edges
# because edge [8,9] has already both directions, its weight has to be halved in A_u

A_u = A + np.transpose(A)
A_u[8,9] = 1
A_u[9,8] = 1

A3_u = np.linalg.matrix_power(A_u,3)



print(A3_u)

[[0. 2. 4. 3. 1. 1. 1. 0. 2. 0.]
 [2. 0. 0. 1. 8. 2. 0. 7. 1. 7.]
 [4. 0. 0. 1. 7. 2. 0. 6. 1. 4.]
 [3. 1. 1. 0. 1. 4. 1. 2. 0. 1.]
 [1. 8. 7. 1. 0. 6. 6. 1. 4. 1.]
 [1. 2. 2. 4. 6. 0. 1. 2. 5. 2.]
 [1. 0. 0. 1. 6. 1. 0. 4. 1. 5.]
 [0. 7. 6. 2. 1. 2. 4. 0. 6. 0.]
 [2. 1. 1. 0. 4. 5. 1. 6. 0. 6.]
 [0. 7. 4. 1. 1. 2. 5. 0. 6. 0.]]


### **Q4. A theoretical question**

Suppose a Python module contains an implementation of a function *maxSpanningTree(G)* that takes as input the adjacency list of graph $G$, with **positive** edge weights, and returns the edges of a maximum weight spanning tree. Further suppose that you can run this function, but you cannot access the code. 

Explain how to use *maxSpanningTree(G)* in order to implement a *minSpanningTree(G)* function. 







Make a copy $G'$ of $G$. Take all weights of $G'$, find the largest weight $w$, and then: negate all weights of $G'$ and add $w+1$. Running *maxSpanningTree(G)* on $G'$ will now give a tree $T'$, which contains the edges of a min spanning tree of $G$. 